databases:
  - name: rails-projects
    databaseName: 
    user: 

services:
  - type: web
    name: 
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-projects
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false