databases:
  - name: full-stack-capstone
    databaseName: cabooky_production_database
    user: cabooky_production_database_user

services:
  - type: web
    name: cabooky-api-v1
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: full-stack-capstone
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false